services:

  payment-service:
    build: ./payment-service-impl
    image: "ghcr.io/${GITHUB_INNOWISE_USERNAME}/${PAYMENT_SERVICE_GH_REPO_NAME}/${PAYMENT_SERVICE_IMAGE_NAME}"
    environment:
      SPRING_PROFILES_ACTIVE: "${APPLICATION_PROFILE}"
      MONGO_DB_URL: "mongodb://payment-service-db:27017/${PAYMENT_SERVICE_DB_NAME}"
      GITHUB_INNOWISE_USERNAME: "${GITHUB_INNOWISE_USERNAME}"
      GITHUB_INNOWISE_TOKEN: "${GITHUB_INNOWISE_TOKEN}"
      PAYMENT_SERVICE_GH_REPO_NAME: "${PAYMENT_SERVICE_GH_REPO_NAME}"
      PAYMENT_SERVICE_IMAGE_NAME: "${PAYMENT_SERVICE_IMAGE_NAME}"
      TOKEN_SECRET: "${TOKEN_SECRET}"
      KAFKA_BOOTSTRAP_URL: "kafka:9092"
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008'
    ports:
      - '9015:8080'
      - '5008:5008'
    expose:
      - '9015' # application api
      - '5007' # debug
    restart: 'always'
    depends_on:
      - 'payment-service-db'
      - 'kafka'

  payment-service-db:
    image: 'mongo:7.0.24-jammy'
    environment:
      MONGO_INITDB_DATABASE: "${PAYMENT_SERVICE_DB_NAME}"
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-payment-service-vol:/data/db'
    restart: 'always'

  kafka:
    image: 'confluentinc/cp-kafka:7.9.3'
    environment:
      KAFKA_NODE_ID: '1'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_LOCALHOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_LOCALHOST://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_LOCALHOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      KAFKA_LOG_DIRS: '/var/lib/kafka/data'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'

      CLUSTER_ID: "${KAFKA_CLUSTER_ID}"

    ports:
      - "29092:29092"
    volumes:
      - 'kafka-data-vol:/var/lib/kafka/data'

volumes:
  mongo-payment-service-vol:
  kafka-data-vol:

networks:
  default:
    external: true
    name: 'innowise-net'