spring:
  application:
    name: 'payment-service'

  profiles:
    active: "${APPLICATION_PROFILE}"

  data:
    mongodb:
      uri: "${MONGO_DB_URL}"
      uuid-representation: 'standard'

  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_URL}"

logging:
  level:
    root: 'info'
    by.innowise.internship.payments.feign.RandomIntClient: 'DEBUG'
    org.springframework.kafka.listener.DeadLetterPublishingRecoverer: 'DEBUG'
    org.springframework.kafka.listener.DefaultErrorHandler: 'DEBUG'
    org.apache.kafka.clients.producer: 'DEBUG'

resilience4j:
  retry:
    instances:
      randomIntServiceRetry:
        max-attempts: 3
        wait-duration: '1s'
        retry-exceptions:
          - 'feign.FeignException'
          - 'by.innowise.common.library.exception.ApplicationException'

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
  endpoint:
    health:
      probes:
        enabled: 'true'
  health:
    livenessState:
      enabled: 'true'
    readinessState:
      enabled: 'true'

application:
  security:
    enabled: 'true'
    secretKey: "${TOKEN_SECRET}"
  feign:
    clients:
      random-org:
        url: "https://www.random.org/integers/"
