spring:
  application:
    name: 'payment-service'

  profiles:
    active: "${APPLICATION_PROFILE}"

  data:
    mongodb:
      uri: "${MONGO_DB_URL}"
      uuid-representation: 'standard'

  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_URL}"

logging:
  level:
    root: 'info'
    by.innowise.internship.payments.feign.RandomIntClient: 'DEBUG'

application:
  feign:
    clients:
      random-org:
        url: "https://www.random.org/integers/"
