name: build & test
on: [ push, pull_request, workflow_dispatch ]
env:
  GITHUB_INNOWISE_USERNAME: vlad-innowise
  GITHUB_INNOWISE_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
  TOKEN_SECRET: ${{ secrets.JWT_TOKEN }}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: build & test
        run: |
          mvn \
          -B \
          -s .github/maven-settings.xml \
          -DskipTests=false \
          verify

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-application
          path: |
            payment-service-impl/target/*.jar
            !payment-service-impl/target/*.jar.original

      - name: upload compiled classes
        uses: actions/upload-artifact@v4
        with:
          name: compiled-classes
          path: payment-service-impl/target/classes

  sonarqube:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Get source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Download compiled classes
        uses: actions/download-artifact@v4
        with:
          name: compiled-classes
          path: payment-service-impl/target/classes

      - name: SonarQube analyze
        uses: SonarSource/sonarqube-scan-action@v5.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=vlad-innowise
            -Dsonar.projectKey=Vlad-Innowise_payment-service
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=payment-service-impl/target/classes
  docker-image:
    runs-on: ubuntu-latest
    needs: [ sonarqube ]
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-application
          path: payment-service-impl/target

      - name: Build Docker Image
        run: |
          cd payment-service-impl
          docker build -t payment-service-image .
